### ISSUE TITLE
Missing pre-built perf compatible metric definition json file for GNR/EMR

### ISSUE THREAD

**Issue by lianhao** [intel/perfmon#109]
On GNR and/or EMR, we can't find the pre-built perf compatible metric definition json file, like the [ file sapphirerapids_metrics_perf.json ](https://github.com/intel/perfmon/blob/main/SPR/metrics/perf/sapphirerapids_metrics_perf.json) for SPR.

How can we generate such file to be used to build linux perf tool from kernel source tree?

**Comment by edwarddavidbaker** [comment]
Closing. Please work with Caleb for GNR and EMR.
