### ISSUE TITLE
mapfile.csv: Add metric entries

### ISSUE THREAD

**Issue by termim** [intel/perfmon#120]
Is it possible to include corresponding entries into mapfile.csv for existing metric files?

**Comment by edwarddavidbaker** [comment]
Adding Perry and Caleb for notifications. @1perrytaylor @calebbiggers

**Comment by termim** [comment]
Hi @edwarddavidbaker, yes, that is exactly what I have in mind. That would make metrics files a 'firs class' citizen of the database.
