### ISSUE TITLE
Fix description of RTM_RETIRED.ABORTED_EVENTS

### ISSUE THREAD

**Issue by aayasin** [intel/perfmon#176]
https://github.com/intel/perfmon/blob/1424ebf3be6f8f3c515fe4296ed35b3c3b19ad39/SPR/events/sapphirerapids_core.json#L6693-L6697

The description refer to "previous 4 categories" while there are only 3 listed.

@andikleen
@edwarddavidbaker

**Comment by vdaneti** [comment]
Description update will be added to RTM_RETIRED.ABORTED_EVENTS
