### ISSUE TITLE
Calculating Metrics from collected events

### ISSUE THREAD

**Issue by kasramgh** [intel/perfmon#193]
Whats the best way to calculate the metrics, given each microarchitecture events (mostly core events) are collected through different tools with various post processing? is there a way to use the available tools in the scripts folder alone or along side perf to calculate the core metrics? events and their counts are collected and available in csv or any other format.

**Comment by captain5050** [comment]
Maybe this can help: https://perf.wiki.kernel.org/index.php/Top-Down_Analysis
