### ISSUE TITLE
cpu_operation_frequency metrics didn't work

### ISSUE THREAD

**Issue by esharkwang** [intel/perfmon#26]
I built a version for Ubuntu20.04 server on AWS EC2 instance. 
After I followed the guidance to cp the icx_metric_perf.json to the perf folder under ubuntu kernel tree, I rebuilt a perf.
The when I used the following command 
perf stat -M cpu_operation_frequency.
The program will give the following error.
ubuntu@ip~/tools/linux-aws-5.15.0/tools/perf$ ./perf stat -M cpu_operating_frequency
event syntax error: '..ed.ref_tsc,system_tsc_freq,cpu_clk_unhalted.thread}:W,duration_ti..'___ parser error
Usage: perf stat [<options>] [<command>]

    -M, --metrics <metric/metric group list>
                          monitor specified metrics or metric groups (separated by ,)

Is anything missed in my configuration?

**Comment by edwarddavidbaker** [comment]
+Caleb and Perry.

**Comment by captain5050** [comment]
You are trying new json with an old version of Linux perf? What version are you trying? It is best to use the latest version, in particular there were a number of Icelake fixes that I believe were added in 6.0.

**Comment by esharkwang** [comment]
The perf version is  5.15.60 which in the Ubuntu 20.04 source code package. You mean this version is too old to apply the perf file in this repository? 

So you would suggest to use perf 6.0? What is the corresponding linux kernel version? I can't upgrade my server to the latest linux kernel version as it will break some dependency.

**Comment by captain5050** [comment]
The perf tool version isn't dependent on the kernel version. Unfortunately Debian/Ubuntu don't distribute the Linux perf tool correctly and try to tie the two together - the maintainer works for Redhat and they do distribute it properly, at Google we roll our own. You can build the tool from source and add the json there, but if you just get the latest 6.1-rc2 code you will get the new json anyway. There has been some talk of Intel helping fixing this Debian packaging problem which would be very much appreciated.

**Comment by esharkwang** [comment]
Thank for the hints, Ian. With perf 6.0 with the latest perf metrics, I can see the perf metrics on icelake. This issue can be closed.
