### ISSUE TITLE
Experimental uncore events?

### ISSUE THREAD

**Issue by gkatev** [intel/perfmon#46]
Hi, I'm looking at the uncore performance event definitions for ICX under perfmon/ICX/events. I'm seeing that some events (e.g. `HITME_` ones) are only included in the "experimental" json. In what regard are the events in that file experimental? Is it to do with the definitions themselves, or are the events themselves in the architecure experimental?

**Comment by edwarddavidbaker** [comment]
Hi @gkatev Thanks for submitting an issue. We expanded event type descriptions at https://github.com/intel/perfmon#performance-monitoring-events to include `uncore_experimental`.

**Comment by gkatev** [comment]
Thanks, I saw the description, that makes sense.

If I had concerns (possibly valid, possibly not :-) ) that some events are not working as expected or that their definitions in the manual/jsons are problematic, should I post my observations as issues here, or follow some other avenue?

**Comment by edwarddavidbaker** [comment]
Thanks @gkatev . For event specific situations email [perfmon-support@intel.com](mailto:perfmon-support@intel.com). If possible, please include platform configuration and relevant workload details.

**Comment by gkatev** [comment]
So I tried to send an email to this address regarding a possible umask typo/conflict in the manual but I'm getting an undeliverable reply with `Recipient address rejected: Access denied`. I'm not sure if you directly manage this email and could fix it if there's a problem with it. Or should I contact Intel support regarding it?

**Comment by edwarddavidbaker** [comment]
We received your message @gkatev . We will investigate undeliverable messages further.
