### ISSUE TITLE
TMA: Introduce TMA_Metrics-full.xlsx

### ISSUE THREAD

**Issue by edwarddavidbaker** [intel/perfmon#52]
Creating an issue to continue the conversation from https://github.com/intel/perfmon/pull/48 .

> Would it be possible to also push the full excel spreadsheet version? The CSV files only contain the first sheet, and having all sheets with all levels is my preference.

----

#### Current TMA files
| .csv | .xlsx |
| --- | --- |
| [TMA_Metrics.csv](https://github.com/intel/perfmon/blob/main/TMA_Metrics.csv) | [TMA_Metrics.xlsx](https://github.com/intel/perfmon/blob/main/TMA_Metrics.xlsx) |
| [TMA_Metrics-full.csv](https://github.com/intel/perfmon/blob/main/TMA_Metrics-full.csv) | |

#### Requested TMA files
`TMA_Metrics-full.xlsx`

**Comment by ayasini** [comment]
Added xls format of TMA full flavor in [tma-metrics-v4.5](https://github.com/intel/perfmon/tree/tma-metrics-v4.5) branch, which is ready for merge.
